# Generated by Django 4.0.4 on 2022-06-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='plot',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Descripción'),
        ),
    ]
