# Generated by Django 4.0.4 on 2022-06-27 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0002_alter_music_plot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='discography',
        ),
        migrations.AddField(
            model_name='music',
            name='author',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
    ]
