# Generated by Django 4.0.5 on 2022-06-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_movie_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cover',
            field=models.ImageField(default='', upload_to='covers', verbose_name='Poster'),
        ),
    ]
